### ISSUE TITLE
Unfortunately, LeakCanary Sample has stopped

### ISSUE THREAD

**Issue by doubleo2** [valentingrigorean/LeakCanaryXamarin#2]
The sample application crashes, whether there is a leak or not. I suspect the bindings are not being created properly

### Running

- Visual Studio Pro 2015
- Android 5.1
- Moto G (XT1034)

### Build Logs

<details>
<pre>
1>------ Rebuild All started: Project: LeakCanary.Watcher, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: LeakCanary.Analyzer, Configuration: Debug Any CPU ------
2>JARTOXML : warning J2X9001: Couldn't load class com/squareup/leakcanary/HeapAnalyzer$1 : java.lang.NoClassDefFoundError: com/squareup/haha/trove/TObjectProcedure
2>JARTOXML : warning J2XA006: missing class error was raised while reflecting com.squareup.haha.perflib.HahaSpy : com/squareup/haha/perflib/Instance
2>JARTOXML : warning J2XA006: missing class error was raised while reflecting com.squareup.leakcanary.HahaHelper : com/squareup/haha/perflib/Field
2>JARTOXML : warning J2XA006: missing class error was raised while reflecting com.squareup.leakcanary.HeapAnalyzer : com/squareup/haha/perflib/io/HprofBuffer
2>JARTOXML : warning J2XA006: missing class error was raised while reflecting com.squareup.leakcanary.LeakNode : com/squareup/leakcanary/Exclusion
2>JARTOXML : warning J2XA006: missing class error was raised while reflecting com.squareup.leakcanary.LeakTraceElement : com/squareup/leakcanary/Exclusion
2>JARTOXML : warning J2XA006: missing class error was raised while reflecting com.squareup.leakcanary.ShortestPathFinder : com/squareup/haha/perflib/Instance
2>JARTOXML : Java HotSpot(TM) Client VM warning : ignoring option UseSplitVerifier; support was removed in 8.0
2>BINDINGSGENERATOR : warning BG8604: top ancestor LeakTraceElement not found for nested type Com.Squareup.Leakcanary.LeakTraceElement.Holder.
2>BINDINGSGENERATOR : warning BG8604: top ancestor LeakTraceElement not found for nested type Com.Squareup.Leakcanary.LeakTraceElement.Type.
2>BINDINGSGENERATOR : warning BG8604: top ancestor ShortestPathFinder not found for nested type Com.Squareup.Leakcanary.ShortestPathFinder.1.
2>BINDINGSGENERATOR : warning BG8604: top ancestor ShortestPathFinder not found for nested type Com.Squareup.Leakcanary.ShortestPathFinder.Result.
2>BINDINGSGENERATOR : warning BG8401: Skipping Com.Squareup.Leakcanary.AnalysisResult.Failure, due to a duplicate field, method or nested type name.
2>  LeakCanary.Analyzer -> C:\...\LeakCanaryXamarin\LeakCanary.Analyzer\bin\Debug\LeakCanary.Analyzer.dll
1>JARTOXML : Java HotSpot(TM) Client VM warning : ignoring option UseSplitVerifier; support was removed in 8.0
1>  LeakCanary.Watcher -> C:\...\LeakCanaryXamarin\LeakCanary.Watcher\bin\Debug\LeakCanary.Watcher.dll
3>------ Rebuild All started: Project: LeakCanary, Configuration: Debug Any CPU ------
3>JARTOXML : Java HotSpot(TM) Client VM warning : ignoring option UseSplitVerifier; support was removed in 8.0
3>BINDINGSGENERATOR : warning BG8102: Class Com.Squareup.Leakcanary.AbstractAnalysisResultService has unknown base type android.app.IntentService.
3>BINDINGSGENERATOR : warning BG8103: Class Com.Squareup.Leakcanary.DisplayLeakService has invalid base type com.squareup.leakcanary.AbstractAnalysisResultService.
3>BINDINGSGENERATOR : warning BG8102: Class Com.Squareup.Leakcanary.Internal.HeapAnalyzerService has unknown base type android.app.IntentService.
3>  LeakCanary -> C:\...\LeakCanaryXamarin\LeakCanary\bin\Debug\LeakCanaryXamarin.dll
</pre>
</details>

**Comment by maxfkdk** [comment]
Hi , any update with that ? Is binding working ?

**Comment by doubleo2** [comment]
@maxfkdk I'm not sure if the latest changes fixed this issue, but after doing a little more research I don't think it makes sense to use LeakCanary on Xamarin projects. Xamarin uses a different garbage collector, so the assumptions LeakCanary makes about when something will be collected do not apply.
